openapi: 3.1.0
info:
  title: Generated API
  version: 1.0.0
paths:
  /health:
    get:
      operationId: anonymous
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
      tags:
      - Index
  /invoices:
    post:
      operationId: anonymous
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
      tags:
      - Index
tags: []
